encoding: UTF-8

theme: jekyll-theme-midnight

author: "Fátima Garay"

lang: "es-ES"

permalink: date

title: [La mamá de Zoe]

description: [Aprendiendo todo de nuevo con mi hija]

paginate_path: "/blog/post:num/"

pagination: 4
